### ISSUE TITLE
Models "rae" and ".noisy_clamped_ae" not found.

### ISSUE THREAD

**Issue by RomeoV** [kylehkhsu/disentangle#1]
In `<repo>/disentangle/models/__init__.py` [here](https://github.com/kylehkhsu/disentangle/blob/e6236d27867b20392b0eb94d2872d33928cca586/disentangle/models/__init__.py#L4-L7) the model files `.rae.py` and `.noisy_clamped_ae.py` are loaded, but not part of the repo, which makes loading the `disentangled` library fail.
I suggest either adding the models or removing the lines :)

**Comment by kylehkhsu** [comment]
Thank you for catching this! Fixed.
